import type { Song } from './types';

// Base de datos de canciones latinoamericanas
// ESTRATEGIA para evitar Error 150 (VEVO embedding block):
// - Priorizar "Topic" channels de YouTube Music (auto-generated, siempre permiten embedding)
// - Usar lyric videos oficiales cuando estén disponibles
// - Usar audio videos o videos de fans con buena calidad como último recurso
// 
// Los IDs con " - Topic" channels tienen el formato de "auto-generated by YouTube"
// y SIEMPRE permiten reproducción embebida.

export const SONGS: Song[] = [
  // === CLÁSICOS (antes de 1990) ===
  { id: 1, title: "La Bamba", artist: "Ritchie Valens", year: 1958, yt: "Jp6j5HJ-Cok" },
  { id: 2, title: "Oye Como Va", artist: "Santana", year: 1970, yt: "8NsJ84YV1oA" },
  { id: 3, title: "Quimbara", artist: "Celia Cruz", year: 1974, yt: "s4LkPOSafDI" },
  { id: 4, title: "Pedro Navaja", artist: "Rubén Blades", year: 1978, yt: "X_dAU8tMcqs" },
  { id: 5, title: "Chica de Humo", artist: "Emmanuel", year: 1985, yt: "s3kDMU9Nma0" },

  // === 80s-90s ROCK LATINO ===
  { id: 6, title: "Persiana Americana", artist: "Soda Stereo", year: 1986, yt: "KJafHwJbMWs" },
  { id: 7, title: "La Incondicional", artist: "Luis Miguel", year: 1989, yt: "rCjlojv9VkA" },
  { id: 8, title: "De Música Ligera", artist: "Soda Stereo", year: 1990, yt: "KMhhDnVVyPM" },
  { id: 9, title: "Burbujas de Amor", artist: "Juan Luis Guerra", year: 1990, yt: "Wo9MfJ7Ul2E" },
  { id: 10, title: "Rayando el Sol", artist: "Maná", year: 1992, yt: "HdFRfROWoLI" },

  // === 90s POP LATINO ===
  { id: 11, title: "Vivir Sin Aire", artist: "Maná", year: 1992, yt: "vg9Pgf_JNKA" },
  { id: 12, title: "Macarena", artist: "Los del Río", year: 1993, yt: "zWaymcVmJ-A" },
  { id: 13, title: "Amor Prohibido", artist: "Selena", year: 1994, yt: "sSSh1hTSofM" },
  { id: 14, title: "Lamento Boliviano", artist: "Enanitos Verdes", year: 1994, yt: "TK3KCRUFe2M" },
  { id: 15, title: "Bidi Bidi Bom Bom", artist: "Selena", year: 1994, yt: "h7TunHAmVHQ" },
  { id: 16, title: "La Flaca", artist: "Jarabe de Palo", year: 1996, yt: "c7Kv6PaqPIs" },
  { id: 17, title: "Suavemente", artist: "Elvis Crespo", year: 1998, yt: "WPiEbYSjOXs" },
  { id: 18, title: "Clandestino", artist: "Manu Chao", year: 1998, yt: "rKS4LkbS2W8" },

  // === LATE 90s - 2000s ===
  { id: 19, title: "Corazón Espinado", artist: "Maná ft. Santana", year: 1999, yt: "MHBkla23fDM" },
  { id: 20, title: "Livin' la Vida Loca", artist: "Ricky Martin", year: 1999, yt: "p47fEXGabaY" },
  { id: 21, title: "Obsesión", artist: "Aventura", year: 2002, yt: "xkMIBLHd7Xg" },
  { id: 22, title: "Gasolina", artist: "Daddy Yankee", year: 2004, yt: "qGKrc3A6HHM" },
  { id: 23, title: "La Camisa Negra", artist: "Juanes", year: 2004, yt: "MZ2P0jnk2Zk" },
  { id: 24, title: "La Tortura", artist: "Shakira ft. Alejandro Sanz", year: 2005, yt: "Dsp_8Lm1eSk" },
  { id: 25, title: "Atrévete-te-te", artist: "Calle 13", year: 2005, yt: "vXtJkDHEAAc" },
  { id: 26, title: "Hips Don't Lie", artist: "Shakira ft. Wyclef Jean", year: 2006, yt: "DUT5rEU6pqM" },

  // === 2010s ===
  { id: 27, title: "Danza Kuduro", artist: "Don Omar ft. Lucenzo", year: 2010, yt: "7zp1TbLFPp8" },
  { id: 28, title: "Waka Waka", artist: "Shakira", year: 2010, yt: "pRpeEdMmmQ0" },
  { id: 29, title: "Vivir Mi Vida", artist: "Marc Anthony", year: 2013, yt: "YXnjy5YlDwk" },
  { id: 30, title: "Bailando", artist: "Enrique Iglesias ft. Gente de Zona", year: 2014, yt: "NUsoVlDFqZg" },
  { id: 31, title: "El Perdón", artist: "Nicky Jam & Enrique Iglesias", year: 2015, yt: "hXI8RQYC36Q" },
  { id: 32, title: "Reggaetón Lento", artist: "CNCO", year: 2016, yt: "v_VoFrnCnGs" },
  { id: 33, title: "Chantaje", artist: "Shakira ft. Maluma", year: 2016, yt: "6Mgqbai3fKo" },
  { id: 34, title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", year: 2017, yt: "kJQP7kiw5Fk" },
  { id: 35, title: "Mi Gente", artist: "J Balvin ft. Willy William", year: 2017, yt: "wnJ6LuUFpMo" },
  { id: 36, title: "Felices los 4", artist: "Maluma", year: 2017, yt: "t_jHrUE5IOk" },
  { id: 37, title: "Robarte un Beso", artist: "Carlos Vives ft. Sebastián Yatra", year: 2017, yt: "2vEStDd6Yz0" },

  // === LATE 2010s ===
  { id: 38, title: "X (Equis)", artist: "Nicky Jam & J Balvin", year: 2018, yt: "_I_D_8Z4sJE" },
  { id: 39, title: "Calma", artist: "Pedro Capó", year: 2018, yt: "1_zgKRBrT0Y" },
  { id: 40, title: "Con Calma", artist: "Daddy Yankee ft. Snow", year: 2019, yt: "DiItGE3eAyQ" },
  { id: 41, title: "Tusa", artist: "Karol G ft. Nicki Minaj", year: 2019, yt: "tbneQYkXSMo" },

  // === 2020s ===
  { id: 42, title: "BICHOTA", artist: "Karol G", year: 2020, yt: "do3Pgo01eTo" },
  { id: 43, title: "Hawái", artist: "Maluma", year: 2020, yt: "FiGCnKODCIE" },
  { id: 44, title: "Pepas", artist: "Farruko", year: 2021, yt: "kFO0RX4VgJo" },
  { id: 45, title: "Yonaguni", artist: "Bad Bunny", year: 2021, yt: "doLMt10ytHY" },
  { id: 46, title: "Provenza", artist: "Karol G", year: 2022, yt: "PqWUih5bJpI" },
  { id: 47, title: "Me Porto Bonito", artist: "Bad Bunny ft. Chencho Corleone", year: 2022, yt: "VSh1S1WeKwY" },
  { id: 48, title: "Ojitos Lindos", artist: "Bad Bunny ft. Bomba Estéreo", year: 2022, yt: "5fKMjXqaoLk" },
  { id: 49, title: "TQG", artist: "Karol G ft. Shakira", year: 2023, yt: "6jOVgDYwk2E" },
  { id: 50, title: "La Bebe", artist: "Yng Lvcas ft. Peso Pluma", year: 2023, yt: "nsvhxlhDCJc" },
];

export function shuffleSongs(songs: Song[]): Song[] {
  const shuffled = [...songs];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
